# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      

    # Set up Node.js for building the JavaScript project
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.10.1' # Adjust the Node.js version if necessary

    - name: Install JavaScript dependencies
      run: npm install
      working-directory: ./gold-kinen-react

    - name: Build JavaScript project
      run: npm run build # Adjust if you have other build scripts
      working-directory: ./gold-kinen-react
    # Set up Java for running Selenium tests
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '21.0.3'
        distribution: 'temurin'
        cache: maven

        

    # - name: Cache Maven packages
    #   uses: actions/cache@v3
    #   with:
    #     path: ~/.m2/repository
    #     key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
    #     restore-keys: ${{ runner.os }}-maven

    - name: Install Maven dependencies
      run: mvn install -f Goldkinen_Regression/goldkinendemo/pom.xml

    - name: Run Selenium tests
      run: mvn test -f Goldkinen_Regression/goldkinendemo/pom.xml

    # If you want to generate a test report
    # - name: Archive test results
    #   if: failure()
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: test-results
    #     path: selenium-tests/target/surefire-reports


    
      

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
